### PR TITLE
Allow each grid item to define whether or not it is draggable/resizable ...

### PR DESCRIPTION
**Pull request by browniefed**
...or not.

### CODE REVIEW

**Comment by STRML** [comment]
See [utils#synchronizeLayoutWithChildren()](https://github.com/STRML/react-grid-layout/blob/master/lib/utils.js#L318) - these properties should also be copied over.

To be honest, since that's not a performance-sensitive function, I think it makes more sense to replace that with an `assign` call instead so we don't have to munge this thing over and over.

I'll make that change first to master so you don't have to.

**Comment by browniefed** [comment]
@STRML sounds good, I wasn't seeing them get copied over when it was defined on the global layout array, didn't check whether or not it was working with defining layouts on the children themselves.

**Comment by STRML** [comment]
No reason to close this, it can be merged after I move to Object.assign() on that bit.

**Comment by browniefed** [comment]
@STRML ha my bad, let me know if you need anything else from me or if it doesn't follow your coding style spec.

**Pull request merged**
