### PR TITLE
Fix grid layout types and defaults

### PR DESCRIPTION
**Pull request by TrySound**
Right now flow types just fail

### CODE REVIEW

**Comment by TrySound** [comment]
Hey, @STRML 
Do you need to help with maintaining this project? I'm interested.

**Comment by STRML** [comment]
Yeah, absolutely. I barely have time for it anymore.

**Comment by TrySound** [comment]
@STRML So, would you like to make me a collaborator? My PRs a critical for my team.

**Comment by STRML** [comment]
Sure. Please continue to open PRs and I'll review - this one LGTM and I'll merge - but I could definitely use the help on more intense review, issue handling, and API direction into 2.x (see #573). Thanks!

**Comment by TrySound** [comment]
Would be good to have patch release with fixed types.

**Comment by STRML** [comment]
Sure.

**Comment by STRML** [comment]
`0.16.1`

**Comment by STRML** [comment]
`0.16.1`

**Pull request merged**
