### PR TITLE
Firefox dragover

### PR DESCRIPTION
**Pull request by Charles-Lamoureux**
This is picking up from a separate PR that is stale: https://github.com/STRML/react-grid-layout/pull/1053
There has been a related issue opened since the original PR: https://github.com/STRML/react-grid-layout/issues/1324

If you try to drop an item over a placeholder in Firefox, the onDrop function is not invoked.

I found that with the current state of the project, it was only necessary to add preventDefault() to the event when using Firefox to resolve this.

### CODE REVIEW

**Comment by STRML** [comment]
Thanks!

**Comment by vocko** [comment]
@STRML Could an npm release be created with this fix, please? And thanks for the whole project, I really love your library!

**Comment by STRML** [comment]
Yep - released as  `1.2.0`.

**Comment by vocko** [comment]
> Yep - released as `1.2.0`.

Thanks heaps mate!

**Comment by sayo96** [comment]
I'm experiencing something strange. Look at this issue - https://github.com/react-grid-layout/react-grid-layout/issues/1838

**Pull request merged**
