### PR TITLE
modified 'synchronizeLayoutWithChildren' method to convert all uses o…

### PR DESCRIPTION
**Pull request by aweber1**
modified 'synchronizeLayoutWithChildren' method to convert all uses of child.key value to int

### CODE REVIEW

**Comment by STRML** [comment]
Happy to accept this, but could you please remove the dist files?

**Comment by aweber1** [comment]
Interesting, I see in the .gitignore that dist/* should be ignored, but it's not ignored in my local repo unless I add "/dist" to the .gitignore. Are you ok with that change to .gitignore?

**Comment by STRML** [comment]
It's a bit misleading - I believe I did a `git add` on those files manually while ignoring the rest of the folder. I want `dist` to be available (for now) for users who want a browser build.

**Comment by aweber1** [comment]
ok, i'll close the PR and submit a separate one without the dist files.

**Comment by STRML** [comment]
No need for that, just:

```bash
git reset HEAD~1
git rm --cached dist/
git commit -m "message"
git push --force
```

**Pull request closed without merging**
