### PR TITLE
Upgrade `react-grid-layout`

### PR DESCRIPTION
**Pull request by thasner**
Fixes https://github.com/STRML/react-grid-layout/issues/560

### CODE REVIEW

**Comment by STRML** [comment]
Thanks!

**Comment by thasner** [comment]
@STRML would it be possible to publish a new/patch version to npm?

**Comment by STRML** [comment]
That's not required; the newest version of `react-resizable` matches the old constraints. You may want to run a new install or regenerate your own lockfile.

**Comment by thasner** [comment]
the bit that's weird is I then need to add an artificial `"react-draggable": "^2.2.6"` dependency into my `package.json` just for this, and it'll eventually become stale.

It turns out this console warning isn't egregious, so I'll survive until you publish, but it still seems that publishing is the "right thing to do" from `react-grid-layout`'s perspective

**Comment by STRML** [comment]
It's not, that's the whole point of these version ranges. Delete the entry
from your lockfile or shrinkwrap file and the package will update.

**Comment by thasner** [comment]
I wasn't aware that npm would default to the newest compliant version.

NPM's [semver docs on `Caret Ranges`](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004) indicate that newer versions are "allowed". (There won't be a conflict if someone else requires a newer version in range)

Anyway, clearing `yarn.lock` and reinstalling did the trick. Thanks.

**Comment by melloc01** [comment]
@STRML @thasner 

I'm still getting the errors as referenced also by my issue #556 
I've made a webpackbin https://www.webpackbin.com/bins/-Kjwr_o7tLT1JAfz9ujE that reproduces the error and you can check it out :+1: (you can check or change the versions on the `Cog` - top right)
I'm also having a perf issue because of this issue.

My lockfile:
```
react-draggable@^2.1.1, react-draggable@^2.2.6:
  version "2.2.6"

react-resizable@^1.4.0:
  version "1.7.0"

react-grid-layout@0.14.6:
  version "0.14.6"
```

**Pull request merged**
