### PR TITLE
Fix for the drag-from-outside example

### PR DESCRIPTION
**Pull request by n1ghtmare**
Fixed some issues with the examples (addressing #996)

### CODE REVIEW

**Comment by STRML** [comment]
Should contain the link from 14 into 15

**Comment by n1ghtmare** [comment]
@STRML Sorry, perhaps I'm missing something, but currently there is a link from 14 to 15 and from 15 back to 14. Unless I misunderstood you.

**Comment by Zacele** [comment]
Hi, have you guys deploy this code on to the live example website?

**Comment by daynin** [comment]
@STRML could you publish docs, pls?

**Comment by Zacele** [comment]
Hi, the example link is working but when I applied it to my project I cannot replicate it. I've inspected the source of I cannot find where is the definition or where is isDroppable or onDrop. So is this gonna be exist in the later version or am I missing something?
Screenshot 2019-09-19 14 13 23

**Comment by daynin** [comment]
@Zacele yes, it'll be available in the next version (which isn't released yet)

**Comment by VishalJadhaoCTS** [comment]
@daynin When will be next version available?

**Comment by marnett-git** [comment]
Hey just something to note - the example doesn't fully work in Firefox, but it does in Chrome.
The outside element isn't draggable for me.

**Comment by daynin** [comment]
@VishalJadhaoCTS sorry, I don't know. Only @STRML can release new version

**Comment by STRML** [comment]
Will do, but need to validate Firefox etc

**Comment by daynin** [comment]
@marnett-git I created an issue https://github.com/STRML/react-grid-layout/issues/1004 and I'll try to fix it

**Comment by raymond-ong** [comment]
I also could not replicate the example. Waiting for the release :-)

**Comment by eating-noodles** [comment]
@STRML hey, although the same question, when will be next version available?we need it

**Pull request merged**
