### PR TITLE
Resizable handles on other corners v2

### PR DESCRIPTION
**Pull request by mariusandra**
This PR is just PR #1052, but synced with the latest master, so it could be merged faster.

I have published this PR as a NPM package [@mariusandra/react-grid-layout](https://www.npmjs.com/package/@mariusandra/react-grid-layout) so I could use it myself now. 

I'll probably delete it once this PR is merged.

### CODE REVIEW

**Comment by josesaranda** [comment]
Please, @STRML  approve this Pull Request.

**Comment by mariusandra** [comment]
This PR doesn't break anything, yet the only thing is that the logic for resizing to the left and top is not intuitive: the boxes resize to the bottom and right:

screencast 2020-05-26 13-52-18

I fixed this myself by only enabling S, SE and E resizing and ignoring the non-intuitive ones. Already for having south and east resizing I think it's worth merging this.

**Comment by josesaranda** [comment]
Then remove these options and create a PR with resizing in S, SE and E corners... if I where the owner or one of maintainers of this repo I'd accept your PR.

**Comment by mariusandra** [comment]
Those are not my changes :). I'm just describing my thoughts on why @STRML didn't merge the previous PR.

**Comment by nebrelbug** [comment]
I'd love this feature!

@mariusandra any chance you could enable GitHub pages on your fork so I could test out the demos?

**Comment by mariusandra** [comment]
@nebrelbug [Here you go](https://react-grid-layout-resize-corners.netlify.app/)

We recently created [dashboards in PostHog](https://posthog.com/blog/the-posthog-array-1-6-0) using the changes in this PR. You can't see it on the screencast, but being able to drag from the bottom and the right side adds a bit of flexibility.

dashboards

**Comment by nebrelbug** [comment]
@mariusandra thanks for the demo! I may update to use this fork :thinking:

**Comment by STRML** [comment]
Keeping an eye on this, there are some fixes in react-resizable to merge first to ensure this works well.

**Comment by Twixes** [comment]
Hi, @STRML, do you think we could get this in?

**Comment by STRML** [comment]
Thanks, I'll remove the stale marking now that react-resizable v2 is out. Merge conflicts need resolution though.

**Comment by Twixes** [comment]
That's great, thanks! When is there going to be an npm release with this? Eager to use in production!

**Pull request merged**
