### PR TITLE
Slightly narrow flow definition for "style" prop

### PR DESCRIPTION
**Pull request by Jabher**
narrowing flow definition for style attribute to make Flow typings more narrowed:
Object -> CSSStyleDeclaration ([bundled Flow class](https://github.com/facebook/flow/blob/v0.64.0/lib/cssom.js#L71))

### CODE REVIEW

**Comment by STRML** [comment]
Great, didn't know about that builtin - thanks.

**Comment by TrySound** [comment]
@Jabher @STRML And now you want to write `width` and `height` and others as strings? It's not nice in react.

**Comment by TrySound** [comment]
Btw it's breaking change.

**Comment by STRML** [comment]
Ah that is indeed an issue. Will revert this barring a better typedef that works w/React.

**Comment by Jabher** [comment]
Weird. Sorry for that.
Will probably spend some time on investigation why definition is implemented in that way

**Comment by Jabher** [comment]
Just... wow.

Flow just do not have constrainted definition for react style prop (in comparison to [TypeScript](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/v15/index.d.ts#L780)); they [are aware of that](https://github.com/facebook/flow/issues/5192) and looks like they do not plan to fix it.
I've also checked some css-in-js solutions with flow typings and still nothing...
Sorry again for that. 

It actually makes me feel sad that we still do not have nice typings for style prop.

**Comment by TrySound** [comment]
@Jabher PR to flow?

**Comment by Jabher** [comment]
Looks so. But I feel it can take significant amount of time, so definitely not today :)
Also it's more question of maintenance first of all, not initial seed.

**Comment by TrySound** [comment]
@Jabher I'm sure it will be maintained similar to native css props. The problem often is lack of time for initial seed.

**Pull request merged**
