### PR TITLE
Add new prop to disable vertical compact

### PR DESCRIPTION
**Pull request by TeaBough**
I've added the ability to disable vertical compact.

### CODE REVIEW

**Comment by browniefed** [comment]
@TeaBough you should also document this new prop in the Grid Layout Props in the README

**Comment by TeaBough** [comment]
Oups, I forgot. It's done.

**Comment by STRML** [comment]
This is good, but is there a reason why the build files have been renamed?

**Comment by TeaBough** [comment]
It's because the rename command is not working the same way on Archlinux (the one in the Makefile). So I've changed it with a combo find/mv. I think that doing the rename this way is more portable.

**Comment by STRML** [comment]
Thanks for the contribution. Could you please rebase this on master? I've already incorporated your `rename` change and the `build/` directory to clean up diffs. I saw this [great article](http://mammal.io/articles/using-es6-today/#publishing-to-npm) about publishing ES6 projects so I've made some changes.

**Comment by benmosher** [comment]
Should this be closed, on account of being merged (in spirit) via #48?

**Comment by TeaBough** [comment]
Yes

**Pull request closed without merging**
