### PR TITLE
fix: dynamic isDraggable and isResizable remount

### LINKED ISSUE #240: dynamic isDraggable isResizable
Hi,
I'm currently dynamically setting isDraggable and isResizable based upon whether you go into an edit mode for our dashboard grid layout.
This works great ... 
Although, whenever one of these changes from false-true and then back again the GridItems are unmounted and remounted.
This means that my statefull components inside a GridItem get unmounted and then remounted .... amounting to their state being blown away.
I wouldn't normally use statefull components but they include c3 graphs which have their own lifecycle outside of react, etc ...
So, is there a way of stopping this behaviour ?
If I change any properties of the child components through a redux connect they don't get unmounted.
Any help would be much appreciated.
/Stephen.

### PR DESCRIPTION
**Pull request by lmachens**
Fixes #240 
Fixes #892

Issue:
Childrens are remounted when isDraggable or isResizable is changed.

Solution:
The `Resizable` and `DraggableCore` parents are always mounted to prevent remount of children.
Use `disabled` to prevent calling drag handlers and hide the resizable handle with css.

### CODE REVIEW

**Comment by lmachens** [comment]
@STRML any update?

**Comment by kravets-levko** [comment]
This PR will also fix #626

**Comment by artemsaveliev** [comment]
Made another way to do it #937 
Not speaking for maintainer, but I am not sure switching to always wrapping with DragggableCore is good. In my version you can still remove DraggableCore by setting isDraggable off.

**Comment by nevalera** [comment]
Any updates on this or #937 ?

The fix for the remounting issue is required for us to be able to use this library.

**Comment by agg23** [comment]
Another ping for this PR to get looked at. This is a pretty major blocker for many scenarios.

**Comment by STRML** [comment]
What performance impact will this have? I am also loathe to always wrap elements when not needed. I would prefer the user to manually hide the handles if they have the desire to make draggability/resizability dynamic.

**Comment by asaveliev** [comment]
> I would prefer the user to manually hide the handles if they have the desire to make draggability/resizability dynamic

Currently entering/exiting editing triggers complete reload of all widgets - depending on scenario, this may not be a great experience. Specifically for us it is expensive as widgets have expensive rendering paths. 

I am not sure there's a way to make draggability dynamic with current version - other than switching each widget to static?

**Comment by n1ghtmare** [comment]
> What performance impact will this have? I am also loathe to always wrap elements when not needed. I would prefer the user to manually hide the handles if they have the desire to make draggability/resizability dynamic.

@STRML As far as performance impact, what are your concerns here? Otherwise, I actually tend to agree with you on the second part (in the sense that, we shouldn't clutter the code-base with various features that can be achieved with some code on the user's side). However in this case I think there is a good use case as others stated.

**Comment by STRML** [comment]
This can be done for resizability per item by hiding the handle via CSS, and for grid items by returning `false` from the grid's `onDragStart(i: string, x: number, y: number, { e, node }: GridDragEvent)` callback.

**Comment by agg23** [comment]
While that is good to know, I don't really consider those solutions to be much more than hacks. In general, I expect React components to dynamically respond to configuration updates with only minor rerendering; that is one of the core constructs of React. The fact that there are `isDraggable` and `isResizable` props that require such hacks if you want them to respond in the "expected" way indicates to me that something more should be done in this area.

**Comment by mitulmk** [comment]
Nudge...

**Comment by mitulmk** [comment]
Great to see progress... What is the "Labeler / label (pull_request)" check that's failing?

**Comment by agg23** [comment]
@STRML, are you strongly opposed to this change? As it stands, is there any likelihood that this gets approved, or should this PR be closed?

**Comment by JohnDDuncanIII** [comment]
> This can be done for resizability per item by hiding the handle via CSS, and for grid items by returning false from the grid's onDragStart(layout, oldItem, newItem, placeholder, e, ?node) callback.

The above worked almost perfectly, but since the `GridItem.jsx` `onDragStart` computes and sets the `dragging` state value before it invokes `this.props.onDragStart && _this.props.onDragStart`, this meant that if I clicked on any disabled dashboard widget when not in edit mode, then `react-grid-layout` would still append the `react-draggable-dragging` `className` to the widget.

This caused a particularly nasty issue where any widget that had been clicked before we entered edit mode would get "stuck" in its "dragging" position until you dragged it away and then back in. If you tried to drag a non-stuck widget over the stuck one, they would just overlap with each other.

Screen Shot 2020-02-10 at 3 46 20 PM

To fix this, I took the aforementioned advice from [STRML](https://github.com/STRML/react-grid-layout/pull/892#issuecomment-532014140) and also utilized some techniques outlined in all of the related issues to reach what I would consider to be the current "canonical" solution to the unmount/remount bug that occurs when you change `isDraggable`/`isResizable`

https://github.com/STRML/react-grid-layout/issues/89
https://github.com/STRML/react-grid-layout/issues/240
https://github.com/STRML/react-grid-layout/issues/362
https://github.com/STRML/react-grid-layout/issues/371
https://github.com/STRML/react-grid-layout/issues/379
https://github.com/STRML/react-grid-layout/issues/626
https://github.com/STRML/react-grid-layout/issues/721
https://github.com/STRML/react-grid-layout/issues/756
https://github.com/STRML/react-grid-layout/issues/1067

```jsx
<StyledReactGridLayout
    ...
    // this completely disables the drag functionality for a GridItem
    draggableHandle={!this.props.editing ? ".not-draggable" : null}
    // this is our internal redux store value that tracks whether we have clicked the edit button
    editing={this.props.editing}
    // these should always be set to true to prevent remounts
    isDraggable
    isResizable
    // if we are editing, we want the default onDragStart functionality
    // if we are not editing, then we return false to disable the internal GridItem onDrag
    onDragStart={() => this.props.editing}
    ...
>
    {...}
</StyledReactGridLayout>
```

```javascript
import styled, { css } from "styled-components"
import RGL, { WidthProvider as provideWidth } from "react-grid-layout"
const ReactGridLayout = provideWidth(RGL)

export const StyledReactGridLayout = styled(ReactGridLayout)`
    position: relative;
    transition: height 100ms ease;

    .react-grid-item {
        box-sizing: border-box;
        transition: all 100ms ease;
        transition-property: left, top;

        .react-resizable-handle {
            display: none;
        }

        ${props => (props.editing) && css`
            .react-resizable-handle {
                display: initial;
            }

            &:hover {
                cursor: pointer;
            }

            &:active {
                background: #dadada;
                cursor: move;
            }
        `}
    }
`
```

**Comment by STRML** [comment]
Alright. I think yall have convinced me that this is worth the rather small bit of overhead that is added in cases where you are not using draggability/resizability. I would rather that this component be easy to use. Merging. I'll cut a release in the next few days when I have time to prepare the changelog and do extra regression testing.

**Comment by STRML** [comment]
Will be released in a few minutes in `0.18.0`.

**Pull request merged**
