### PR TITLE
Pass handle option to react-resizable

### PR DESCRIPTION
**Pull request by typeetfunc**
Problem: we can't pass custom resize handle to react-resizable
Solution: I add prop 'resizeHandle' to ReactGridLayout

### CODE REVIEW

**Review by daynin — APPROVED** [review]

**Comment by STRML** [comment]
Clean!!!! Thank you.

**Comment by typeetfunc** [comment]
@STRML Can you release a new  package version with this changes?

**Comment by TikTikTik21** [comment]
The resizeHandle props is still not working

**Comment by BboyAwey** [comment]
The package on npm still not work with this resizeHandle prop. Weird~~~

**Comment by AaronPowell96** [comment]
> The package on npm still not work with this resizeHandle prop. Weird~~~

Works for me mate, pass a function and then return an element I use a switch to check if the axis is e s se etc.

Why isnt this also added for dragHandle?

**Pull request merged**
