### PR TITLE
fix(drag): external drag must trigger activeDrag

### LINKED ISSUE #1152: Drag from outside is missing placeholder
Run /examples/15-drag-from-outside.html using version 0.18.x and note that the placeholder doesn't show up at all like it does in v0.17: https://strml.github.io/react-grid-layout/examples/15-drag-from-outside.html

### PR DESCRIPTION
**Pull request by paul-sachs**
Fixes #1152. When a drag event happens from an external element,
we should mimic the drag activity.

### CODE REVIEW

**Comment by STRML** [comment]
Thanks for the contribution @paul-sachs. 

I'm not sure I understand how this broke between 0.17 and 0.18. It stands to reason that a patch to restore the old behavior shouldn't be this involved. Do you know?

Could you add a test for this? I've added some basic scaffolding (long overdue) for Enzyme tests in `master`. If you rebase upon it, it should be easy enough to add this.

**Comment by STRML** [comment]
Bisect shows 1078b14582f424838947c8b0cf386eb6b45163b6 introduced the bug.

**Comment by paul-sachs** [comment]
@STRML I'll take a closer look. I would also like to keep changes minimum. I'll look to rebase and integrate some tests, though drag events are notoriously complicated with nodejs dom implementations, so we'll see how that goes.

**Comment by STRML** [comment]
Hey @paul-sachs. I got it working. PR to come shortly.

**Comment by paul-sachs** [comment]
Closing in favour of #1164

**Pull request closed without merging**
