### PR TITLE
Horizontal compact 2

### PR DESCRIPTION
**Pull request by victor5114**
* [feature] Rebase @STRML work for horizontal Compaction support ([#66][i66])

I found out that you had already done most of the job so I simply decided to rebase (manually) your horizontalCompact branch work with the latest master version (+ adding few function doc).
No addionnal tests were added though.

[i66]: https://github.com/STRML/react-grid-layout/issues/66

Bear with my it's me first pull request ;-) Feel free to comment if I did it wrong.

### CODE REVIEW

**Comment by STRML** [comment]
Thanks for the rebase. Will need to test this then can do a minor.

**Comment by victor5114** [comment]
Brilliant ! I'm starting with React and curious to know how to manage tests with it. Will catch up with this repo if I can come up with a proper solution somehow.

And many thanks for RGL. it's working nicely with my projects so far.

**Comment by STRML** [comment]
Long after I built this repo, I started using https://github.com/airbnb/enzyme in combination with Jest, which works great. A basic suite would use Enzyme for behavioral tests, and take snapshots (so easy!) to verify output.

**Comment by victor5114** [comment]
Nice. I'll give it a try then.

**Comment by alisd23** [comment]
Any update on this?

**Comment by GiovanniFrigo** [comment]
Would love an update on this as well. horizontalCompat would be a great feature to have!

**Comment by luangch** [comment]
Any update on this?

**Comment by andrewhathaway** [comment]
Hey @STRML, can we get this out sometime soon? Horizontal compacting is the way to go! :D

**Comment by vladPovalii** [comment]
Hey @STRML and  @victor5114, thanks for the horizontal compacting feature and for the branch! I`ve really needed it!

**Comment by matt-erhart** [comment]
This would be great to have.

**Comment by STRML** [comment]
Merged in 9b1260d4c41eb900a1e853277c4711114369de0b

**Pull request closed without merging**
