### PR TITLE
Added support for dragging from external sources

### PR DESCRIPTION
**Pull request by artemsaveliev**
Adds support for dragging elements from external sources to support #842 
As a showcase, the toolbox example has been updated to drag items back on the grid 

Fixes the path to commons bundle same as #937

### CODE REVIEW

**Comment by VishalJadhaoCTS** [comment]
Hi, toolbox example doesnt seem to be updated to support dragging from external sources.

**Comment by artemsaveliev** [comment]
@VishalJadhaoCTS 
> Hi, toolbox example doesnt seem to be updated to support dragging from external sources.
If you are cherry-picking on top of already-built clone, you'll have to rebuild the library _and_ examples for the new toolbox example to be generated. 

To use new feature, you have to delete one of the tiles for it to show up in toolbox - then you can drag back from toolbox to the grid.

**Comment by VishalJadhaoCTS** [comment]
I am referring to https://strml.github.io/react-grid-layout/examples/14-toolbox.html
when I delete one of the Tile, it goes to toolbox which is fine. But when I try to drag and drop that Tile from the toolbox to grid, it doesn't work. If I click on the tile, it goes to the previous position in grid but I was really looking for drag and drop.

**Comment by artemsaveliev** [comment]
Not sure why it's not working for you - the branch includes updated examples so you can just run `npm run dev` to see the example.
If you are rebuilding from scratch, make sure you build examples too, `npm run build-example` and `npm run dev`

react grid draganddrop example

**Comment by VishalJadhaoCTS** [comment]
@artemsaveliev how do I get this source code? Master branch doesnt have this code.

**Comment by daynin** [comment]
@artemsaveliev sorry, I missed your PR and added it here https://github.com/STRML/react-grid-layout/pull/980

**Comment by mikefordweb** [comment]
Toolbox example doesn't work for me.  It won't allow me to drag items from the toolbox into the grid.

**Pull request closed without merging**
