### PR TITLE
Implemented react 0.14.0 and removed deprecated methods

### PR DESCRIPTION
**Pull request by stha**
See title

### CODE REVIEW

**Comment by tony99nyr** [comment]
+1

**Comment by NoahMarconi** [comment]
@stha are you able to get this to run without corresponding changes in `react-draggable` and `react-resizable`?

**Comment by jason-henriksen** [comment]
can this be used without it yet being merged in?   
Maybe a bundled .js file that could be used until the npm released work is ready?

**Comment by AlastairTaft** [comment]
Same question as jason-henriksen. 

How do I use this without it being merged in yet? I've checked out stha's repo and linked it with `npm link`, however when running it says I have two versions of React running which isn't compatible. I'm guessing I can't include the built version of this repository with `import ReactGridLayout from 'react-grid-layout'` as the `npm run build` script compiles the current version of React into the webpack compiled files. 

I also tried `import ReactGridLayout from 'react-grid-layout/lib/ReactGridLayout.jsx'` but I can't figure out what js-loader to use with webpack to get it to not complain about syntax errors.

**Comment by stha** [comment]
@NoahMarconi I'm only using the responsive grid, without `react-draggable` and `react-resizable`. Its running pretty fine with the changes i applied in the PR.

And thats how i use this version (I'm using webpack to bundle the files):

package.json (i'm using the master, because there is another patch included):
```
"dependencies": {
...json
     "react-grid-layout": "git+https://github.com/stha/react-grid-layout.git#master"
}
```

script.jsx:
```jsx
'use strict';

var React = require("react");
var ResponsiveReactGridLayout  = require('react-grid-layout').Responsive;

...

return (
			<ResponsiveReactGridLayout
				className="layout row"
				layouts={layout}
				cols={{lg: 6, md: 6, sm: 6, xs: 2, xxs: 2}}
				rowHeight={this.state.rowHeight}
            >
);
```

**Comment by AlastairTaft** [comment]
+1 Thanks

**Comment by STRML** [comment]
I would merge this, but `v0.9.x` is broken as a whole due to some limitations in how we control `react-draggable` and `react-resizable`. In a pinch I may try to fix that so this can get merged, but I'm working to integrate `v1` of draggable and resizable in the [next](https://github.com/STRML/react-grid-layout/tree/next) branch.

**Comment by STRML** [comment]
This is fixed in `next` and released in `0.10.0-beta0`, thanks for the contribution.

**Pull request closed without merging**
