### PR TITLE
Bugfix: Draggable cancel selectors

### PR DESCRIPTION
**Pull request by RiiD**
Cancel selectors should be separated with commas.

### CODE REVIEW

**Comment by STRML** [comment]
No need for the array join - could be:

```js
const cancelSelector = ".react-resizable-handle" + (this.props.cancel ? "," + this.props.cancel : "");
```

**Comment by STRML** [comment]
(by the way, no need to make a new PR, just amend and force-push so we can keep context)

**Comment by RiiD** [comment]
Done.
It is my first pull request and I don't know all the stuff about it :)

**Comment by STRML** [comment]
:+1: Thanks!

**Pull request merged**
