### PR TITLE
Allow container padding to be set independently of margin

### PR DESCRIPTION
**Pull request by seanich**
This is just a simple change to support setting the padding of the grid container independently of the spacing between items. In my particular use case this allows the grid items to align with the edges of the container without any hacks.

The padding can now be set via the `containerPadding` prop. It is an array of two numbers [x, y] just like `margin`. If the `containerPadding` prop is omitted the previous behaviour of using the margin settings as padding is used.

I've also changed the CSS `box-sizing` of grid elements in the examples since the extra width added by the borders becomes quite apparent when `containerPadding` is set to `[0,0]`.

### CODE REVIEW

**Comment by slestang** [comment]
I really want this PR to be merge so I solve the conflict and updated the code to work with current master:
https://github.com/slestang/react-grid-layout/commit/9a502de6bea4c6a01a291f70f303c3f458580eb2

How we can help to have this merged?

**Comment by enriquecaballero** [comment]
+1

**Comment by seanich** [comment]
I've updated the code to work with the current master again. Sorry for taking a while to respond on this!

Let me know if there's anything else I can do to help have this merged :)

**Comment by STRML** [comment]
:+1: Could you please remove the `dist` files from the PR?

**Comment by seanich** [comment]
Done.

**Comment by STRML** [comment]
screen shot 2016-08-08 at 9 48 43 pm

:shipit:

**Pull request merged**
