### PR TITLE
Bump react-resizable to 1.10.0

### PR DESCRIPTION
**Pull request by nguymin4**
This PR fixes https://github.com/STRML/react-grid-layout/issues/1159

### CODE REVIEW

**Comment by nguymin4** [comment]
@STRML Hi Samuel, when you have time can you take a look at this PR. Thanks.

**Comment by STRML** [comment]
This is not necessary, caret version ranges will resolve the latest 1.x version if available. Please simply clear your lockfile in your own project.

**Comment by STRML** [comment]
Ah, I see, this is actually required at runtime due to our new support of `transformScale`. I'll merge this.

**Comment by STRML** [comment]
Thanks and sorry for the misunderstanding.

**Comment by nguymin4** [comment]
:+1:

**Comment by dospolov** [comment]
@STRML animations does not work anymore with this PR

**Pull request merged**
