### PR TITLE
Issue #356: Flatten the JSX hierarchy in children to stop '_grid' und…

### PR DESCRIPTION
**Pull request by j-e-harris**
Thanks for submitting a pull request to RGL!

Please reference an open issue. If one has not been created, please create one along with a failing
example or test case.

Please do not commit built files (`/dist`) to pull requests. They are built only at release.

…efined error

### CODE REVIEW

**Comment by STRML** [comment]
I'm not certain I understand the issue - can you explain?

**Comment by j-e-harris** [comment]
What i found was that when the 'children' parameter passed into the synchronizeLayoutWithChildren function is an array containing sub-arrays, the function fails. Specifically this is because line 375 in lib/utils.js cannot handle a child element that is actually an array:
`if (process.env.NODE_ENV !== 'production' && child.props._grid) {`

This usually happens when you are inserting elements into JSX through a mechanism such as (example only):
`<ul>
        {this.props.results.map(function(result) {
           return <ListItemWrapper key={result.id} data={result}/>;
        })}
</ul>`

Here is a link to the React documentation that will assist:
https://facebook.github.io/react/docs/multiple-components.html#dynamic-children

Recommend you try something like this within a ResponsiveGridLayout and see the result.

Thanks for checking this out. Its actually causing some probs with a dashboard I'm building so it would be great to fix it.

**Comment by STRML** [comment]
Yeah, `children` could actually be all kinds of things, like a keyed fragment.

Best to use `React.Children.map` instead. I'm going to fix this in a separate commit.

**Comment by STRML** [comment]
This is fixed in https://github.com/STRML/react-grid-layout/commit/eac7e0817ab71813c413b1e22f387ccf66ec64ce which was released in `0.13.7`. Thanks for the contribution!

**Pull request closed without merging**
