### PR TITLE
Add preventCollision options based on #385 and @nikolas' example

### PR DESCRIPTION
**Pull request by Rhjulskov**
Added preventCollision property based on existing, non-active PR #385.
Listened to feedback from #385 and adjusted here.

### CODE REVIEW

**Comment by STRML** [comment]
Thanks for the rework. Could you please remove the `dist/` files?

**Comment by Rhjulskov** [comment]
@STRML I've reversed the two dist files

**Comment by keydunov** [comment]
+

**Comment by 9teen90nine** [comment]
👍 need that too

**Comment by ifokeev** [comment]
Up

**Comment by quave** [comment]
👍

**Comment by Rhjulskov** [comment]
@STRML Can I do anything to get this merged? :)

**Pull request merged**
